
- name: Install apt-transport-https
  apt:
    name: apt-transport-https

- name: Install software properties common
  apt:
    name: software-properties-common

- name: Install wget
  apt:
    name: wget

- name: Get package for Grafana
  shell: wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -
  become: true
  become_user: root

- name: Add stable release repository
  shell: echo "deb https://packages.grafana.com/enterprise/deb stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list
  become: true
  become_user: root

- name: Run apt get update
  apt:
    update_cache: yes
  become: true
  become_user: root

- name: Install Grafana
  apt:
    name: grafana-enterprise
  become: true
  become_user: root
  notify: restart grafana
