- name: Install apt-transport-https
  apt:
    name: apt-trasnport-https

- name: Install wget
  apt:
    name: software-properties-common wget

- name: Get package for Grafana
  shell: wget -q -O - https://packages.grafana.gpg.key | sudo apt-key add -

- name: Add stable release repository
  shell: echo "deb https://packages.grafana.com/enterprise/deb stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list

- name: Run apt get update
  apt:
    update_cache: yes

- name: Install Grafana
  apt:
    name: grafana-enterprise
