- name: Install required packages
  apt:
    name:
      - debian-keyring
      - debian-archive-keyring
      - apt-transport-https

- name: Get key
  shell: curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg

- name: Get release
  shell: curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list

- name: Install caddy
  apt:
    name: caddy
    update_cache: yes

- name: Copy caddy file
  template:
    src: "Caddyfile.j2"
    dest: /etc/caddy/Caddyfile
  notify: restart caddy
  become: true
  become_user: root
