---
blackbox_exporter_version: 0.19.0

blackbox_exporter_web_listen_address: "0.0.0.0:9115"

blackbox_exporter_cli_flags: {}
# blackbox_exporter_cli_flags:
#   log.level: "warn"

blackbox_exporter_configuration_modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      method: GET
      valid_status_codes: []
