- name: Install website
  apt:
    deb: https://github.com/jackmford/personal-website-MK3/releases/download/v0.0.7/personal-website-MK3_linux_amd64.deb
    update_cache: yes
  become: yes
  become_user: root