- name: create prometheus group
  group:
    name: prometheus
    system: true
    state: present
  become: true
  become_user: root

- name: create prometheus user
  user:
    name: prometheus
    group: prometheus
    system: true
    shell: "/usr/bin/nologin"
    state: present
  become: true
  become_user: root

- name: create prometheus data directory
  file:
    path: "{{ prometheus_db_dir }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: 0755
  become: true
  become_user: root

- name: create prometheus conf/alert dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: prometheus
    mode: 0770
  with_items:
    - "{{ prometheus_config_dir }}"
    - "{{ prometheus_config_dir }}/rules"

- name: download prometheus tar
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version}}/prometheus-{{ prometheus_version }}.{{ prometheus_arch }}.tar.gz"
    dest: "/tmp/prometheus_{{ prometheus_version }}.{{ prometheus_arch }}.tar.gz"
  become: true
  become_user: root

- name: unzip prometheus tar
  unarchive:
    src: "/tmp/prometheus_{{ prometheus_version}}.{{ prometheus_arch}}.tar.gz"
    dest: /tmp
    creates: "/tmp/promtheus_{{ prometheus_version }}.{{ prometheus_arch }}/prometheus"
    remote_src: true
  become: true
  become_user: root

- name: copy temporary binary files
  copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.{{ prometheus_arch }}/{{ item }}"
    dest: "{{ prometheus_install_dir }}/{{ item }}"
    mode: 0755
    owner: root
    group: root
    remote_src: true
  with_items:
    - prometheus
    - promtool
  become: true
  become_user: root
  notify:
    - restart prometheus

- name: copy official console templates
  copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.{{ prometheus_arch }}/{{ item }}/"
    dest: "{{ prometheus_config_dir }}/{{ item }}/"
    mode: 0755
    owner: prometheus 
    group: prometheus 
    remote_src: true
  with_items:
    - console_libraries
    - consoles
  become_user: root
  become: true
  notify:
    - restart prometheus

- name: copy alert rules configuration file
  template:
    src: "alert.rules.j2"
    dest: "{{ prometheus_config_dir }}/rules/ansible_managed.rules"
    owner: root 
    group: prometheus
    mode: 0640
    validate: "{{ prometheus_install_dir }}/promtool check rules %s"
  become_user: root
  become: true
  notify:
    - reload prometheus

- name: configure prometheus 
  template:
    src: "prometheus.yml.j2"
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    owner: root 
    group: prometheus
    mode: 0640
    validate: "{{ prometheus_install_dir }}/promtool check config %s"
  become_user: root
  become: true
  notify:
    - reload prometheus

- name: configure prometheus web 
  template:
    src: "web.yml.j2"
    dest: "{{ prometheus_config_dir }}/web.yml"
    owner: root 
    group: prometheus
    mode: 0640
  become_user: root
  become: true
  notify:
    - reload prometheus

- name: create prometheus systemd service unit
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: 0644
  become_user: root
  become: true
  notify:
    - restart prometheus

- name: ensure prometheus service is started and enabled
  systemd:
    daemon_reload: true
    name: prometheus
    state: started
    enabled: true
  become_user: root
  become: true
