- name: restart flask
  systemd:
    name: "{{ flask_app_service_name }}"
    state: restarted
  become: true
  become_user: root

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
  become: true
  become_user: root
